[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "A demonstration of a Damn Vulnerable MCP Server for educational purposes."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
]
